"""initial_schema

Revision ID: dd022028e5bf
Revises: 
Create Date: 2026-01-09 20:10:45.738154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd022028e5bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'TXT', 'MD', name='documenttype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'CHUNKING', 'EMBEDDING', 'ANALYZING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_file_type', 'documents', ['file_type'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('processing_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('metric_type', sa.Enum('DOCUMENT_UPLOAD', 'DOCUMENT_PROCESSING', 'TEXT_EXTRACTION', 'CHUNKING', 'EMBEDDING', 'AI_ANALYSIS', 'CHAT_QUERY', 'RETRIEVAL', name='metrictype'), nullable=False),
    sa.Column('operation_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_created_at', 'processing_metrics', ['created_at'], unique=False)
    op.create_index('idx_metrics_success', 'processing_metrics', ['success'], unique=False)
    op.create_index('idx_metrics_type', 'processing_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_processing_metrics_document_id'), 'processing_metrics', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_metrics_session_id'), 'processing_metrics', ['session_id'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_metrics_category', 'system_metrics', ['metric_category'], unique=False)
    op.create_index('idx_system_metrics_name', 'system_metrics', ['metric_name'], unique=False)
    op.create_index('idx_system_metrics_recorded_at', 'system_metrics', ['recorded_at'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('document_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    op.create_index('idx_sessions_document_id', 'chat_sessions', ['document_id'], unique=False)
    op.create_index('idx_sessions_is_active', 'chat_sessions', ['is_active'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_chunk_index', 'document_chunks', ['chunk_index'], unique=False)
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_document_id', 'document_insights', ['document_id'], unique=False)
    op.create_index('idx_insights_type', 'document_insights', ['insight_type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('context_chunks', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('suggested_questions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_messages_role', 'chat_messages', ['role'], unique=False)
    op.create_index('idx_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_messages_role', table_name='chat_messages')
    op.drop_index('idx_messages_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_insights_type', table_name='document_insights')
    op.drop_index('idx_insights_document_id', table_name='document_insights')
    op.drop_table('document_insights')
    op.drop_index('idx_chunks_document_id', table_name='document_chunks')
    op.drop_index('idx_chunks_chunk_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_sessions_is_active', table_name='chat_sessions')
    op.drop_index('idx_sessions_document_id', table_name='chat_sessions')
    op.drop_index('idx_sessions_created_at', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_system_metrics_recorded_at', table_name='system_metrics')
    op.drop_index('idx_system_metrics_name', table_name='system_metrics')
    op.drop_index('idx_system_metrics_category', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_processing_metrics_session_id'), table_name='processing_metrics')
    op.drop_index(op.f('ix_processing_metrics_document_id'), table_name='processing_metrics')
    op.drop_index('idx_metrics_type', table_name='processing_metrics')
    op.drop_index('idx_metrics_success', table_name='processing_metrics')
    op.drop_index('idx_metrics_created_at', table_name='processing_metrics')
    op.drop_table('processing_metrics')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_file_type', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###

